### ISSUE TITLE
Fix imports in psi-mi

### ISSUE THREAD

**Issue by cmungall** [MICommunity/psimi#17]
See https://github.com/owlcs/owlapi/issues/523

You should always use purls for imports, e.g

import: http://purl.obolibrary.org/obo/pato.obo
import: http://purl.obolibrary.org/obo/uo.obo

In fact we recommend that these are OWL. 

import: http://purl.obolibrary.org/obo/pato.owl
import: http://purl.obolibrary.org/obo/uo.owl

You can use an OboEdit catalog to have OE resolve these to a local obo cache. But really you should stop using OE, we do not support it any more. Contact me if you have problems

**Comment by colin-combe** [comment]
This PSI-MI project is not really in use, and something should be done with it to stop it continuing to be a source of confusion. This PSI-MI project was only used to extract everything from google code. 

Is https://github.com/MICommunity/PSI-JAMI the project that the issue you mention applies to?

I suggest moving this PSIMI project somewhere rather than deleting it? It preserved the revision history whereas some of the other moves from google code haven't.

**Comment by cmungall** [comment]
Looks like it should have actually been psi-ms...
